AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Single Step Function that executes ALL Glue jobs passed as input,
  continuing even if some jobs fail. Collects results and reports at the end.
  Pure CloudFormation template - no SAM dependencies.

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  AlarmSNSTopicArn:
    Type: String
    Description: SNS Topic ARN for CloudWatch Alarm notifications
    Default: ''

Conditions:
  HasSNSTopic: !Not [!Equals [!Ref AlarmSNSTopicArn, '']]

Resources:
  #============================================================================
  # IAM Role
  #============================================================================

  GlueJobExecutorRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-sfn-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: GlueJobExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJobRuns
                  - glue:BatchStopJobRun
                Resource: '*'
        - PolicyName: CloudWatchAlarmActions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:SetAlarmState
                Resource:
                  - !Sub 'arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:${AWS::StackName}-sfn-failure'

  #============================================================================
  # CloudWatch Alarm
  #============================================================================

  StepFunctionFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-sfn-failure'
      AlarmDescription: Alarm triggered when Step Function execution fails
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref GlueJobExecutorStateMachine
      AlarmActions:
        - !If [HasSNSTopic, !Ref AlarmSNSTopicArn, !Ref 'AWS::NoValue']
      TreatMissingData: notBreaching

  #============================================================================
  # Single Step Function - Executes ALL Glue jobs, continues on failure
  # 
  # Input format:
  # {
  #   "glueJobs": "job1,job2,job3"
  # }
  #
  # Behavior:
  # - Executes all jobs sequentially
  # - If a job fails, catches error and continues to next job
  # - At the end, checks if any failures occurred
  # - Reports success only if ALL jobs succeeded
  #============================================================================

  GlueJobExecutorStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${AWS::StackName}-glue-executor'
      RoleArn: !GetAtt GlueJobExecutorRole.Arn
      StateMachineType: STANDARD
      DefinitionString: !Sub |
        {
          "Comment": "Executes ALL Glue jobs even if some fail. Input: { \"glueJobs\": \"job1,job2,job3\" }",
          "StartAt": "ValidateInput",
          "States": {
            "ValidateInput": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.glueJobs",
                  "IsPresent": true,
                  "Next": "SplitJobsList"
                }
              ],
              "Default": "InputError"
            },
            "InputError": {
              "Type": "Fail",
              "Error": "InvalidInput",
              "Cause": "Missing required field 'glueJobs'. Expected input: { \"glueJobs\": \"job1,job2,job3\" }"
            },
            "SplitJobsList": {
              "Type": "Pass",
              "Parameters": {
                "jobs.$": "States.StringSplit($.glueJobs, ',')",
                "originalInput.$": "$"
              },
              "Next": "ExecuteAllGlueJobs"
            },
            "ExecuteAllGlueJobs": {
              "Type": "Map",
              "ItemsPath": "$.jobs",
              "MaxConcurrency": 1,
              "ItemProcessor": {
                "ProcessorConfig": {
                  "Mode": "INLINE"
                },
                "StartAt": "RunGlueJob",
                "States": {
                  "RunGlueJob": {
                    "Type": "Task",
                    "Resource": "arn:aws:states:::glue:startJobRun.sync",
                    "Parameters": {
                      "JobName.$": "$"
                    },
                    "ResultPath": "$.jobResult",
                    "Catch": [
                      {
                        "ErrorEquals": ["States.ALL"],
                        "ResultPath": "$.error",
                        "Next": "MarkJobAsFailed"
                      }
                    ],
                    "Next": "MarkJobAsSucceeded"
                  },
                  "MarkJobAsSucceeded": {
                    "Type": "Pass",
                    "Parameters": {
                      "jobName.$": "$",
                      "status": "SUCCEEDED",
                      "error": null
                    },
                    "End": true
                  },
                  "MarkJobAsFailed": {
                    "Type": "Pass",
                    "Parameters": {
                      "jobName.$": "$.jobName",
                      "status": "FAILED",
                      "error.$": "$.error"
                    },
                    "End": true
                  }
                }
              },
              "ResultPath": "$.jobResults",
              "Next": "CheckForFailures"
            },
            "CheckForFailures": {
              "Type": "Pass",
              "Parameters": {
                "jobResults.$": "$.jobResults",
                "originalInput.$": "$.originalInput",
                "failedJobs.$": "States.ArrayGetItem(States.StringSplit(States.JsonToString($.jobResults), 'FAILED'), 0)"
              },
              "Next": "EvaluateResults"
            },
            "EvaluateResults": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.failedJobs",
                  "StringMatches": "*jobName*",
                  "Next": "TriggerFailureAlarm"
                }
              ],
              "Default": "AllJobsSucceeded"
            },
            "TriggerFailureAlarm": {
              "Type": "Task",
              "Resource": "arn:aws:states:::aws-sdk:cloudwatch:setAlarmState",
              "Parameters": {
                "AlarmName": "${AWS::StackName}-sfn-failure",
                "StateValue": "ALARM",
                "StateReason.$": "States.Format('One or more Glue jobs failed. Jobs: {}', $.originalInput.glueJobs)"
              },
              "ResultPath": "$.alarmResult",
              "Next": "PartialFailure"
            },
            "PartialFailure": {
              "Type": "Fail",
              "Error": "PartialGlueJobFailure",
              "Cause": "One or more Glue jobs failed. All jobs were attempted. Check jobResults for details."
            },
            "AllJobsSucceeded": {
              "Type": "Succeed"
            }
          }
        }

Outputs:
  StateMachineArn:
    Description: ARN of the Glue Job Executor Step Function
    Value: !Ref GlueJobExecutorStateMachine
    Export:
      Name: !Sub '${AWS::StackName}-StateMachineArn'

  StateMachineName:
    Description: Name of the Step Function
    Value: !Sub '${AWS::StackName}-glue-executor'

  ExecuteExample:
    Description: Example execution command
    Value: !Sub |
      aws stepfunctions start-execution --state-machine-arn arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AWS::StackName}-glue-executor --name "exec-$(date +%s)" --input '{"glueJobs":"job1,job2,job3"}'