AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Master Step Function executing 5 child Step Functions in parallel.
  Each child runs 30 Glue jobs sequentially.
  Child failure does NOT fail master. SNS notification sent for failures.

Globals:
  Function:
    Timeout: 900

Resources:

  ############################
  # SNS Topic for Failures
  ############################
  StepFunctionFailureTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: stepfunction-child-failure

  ############################
  # IAM Role for Step Functions
  ############################
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: stepfunctions-glue-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsGluePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                  - glue:GetJobRuns
                Resource: "*"
              - Effect: Allow
                Action:
                  - states:StartExecution
                  - states:DescribeExecution
                Resource: "*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref StepFunctionFailureTopic

  ##################################################
  # CHILD STEP FUNCTION (Reusable for all threads)
  ##################################################
  ChildGlueStepFunction:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: child-glue-runner
      Role: !GetAtt StepFunctionsRole.Arn
      Definition:
        StartAt: RunGlueJobs
        States:
          RunGlueJobs:
            Type: Map
            ItemsPath: $.GlueJobs
            MaxConcurrency: 1
            Iterator:
              StartAt: StartGlueJob
              States:
                StartGlueJob:
                  Type: Task
                  Resource: arn:aws:states:::glue:startJobRun.sync
                  Parameters:
                    JobName.$: "$"
                  Catch:
                    - ErrorEquals: ["States.ALL"]
                      ResultPath: $.error
                      Next: FailChild
                  End: true

          FailChild:
            Type: Fail
            Cause: GlueJobFailed
            Error: GlueJobExecutionFailed

  ##################################################
  # MASTER STEP FUNCTION
  ##################################################
  MasterStepFunction:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: master-glue-orchestrator
      Role: !GetAtt StepFunctionsRole.Arn
      Definition:
        StartAt: ParallelChildren
        States:
          ParallelChildren:
            Type: Parallel
            Branches:

              # -------- Child 1 --------
              - StartAt: Child1
                States:
                  Child1:
                    Type: Task
                    Resource: arn:aws:states:::states:startExecution.sync
                    Parameters:
                      StateMachineArn: !Ref ChildGlueStepFunction
                      Input:
                        GlueJobs:
                          - glue-job-1
                          - glue-job-2
                          - glue-job-3
                          # ... up to 30
                    Catch:
                      - ErrorEquals: ["States.ALL"]
                        ResultPath: $.error
                        Next: NotifyFailure1
                    End: true

                  NotifyFailure1:
                    Type: Task
                    Resource: arn:aws:states:::sns:publish
                    Parameters:
                      TopicArn: !Ref StepFunctionFailureTopic
                      Message:
                        Child: Child1
                        Status: FAILED
                        Error.$: $.error
                    End: true

              # -------- Child 2 --------
              - StartAt: Child2
                States:
                  Child2:
                    Type: Task
                    Resource: arn:aws:states:::states:startExecution.sync
                    Parameters:
                      StateMachineArn: !Ref ChildGlueStepFunction
                      Input:
                        GlueJobs:
                          - glue-job-a
                          - glue-job-b
                    Catch:
                      - ErrorEquals: ["States.ALL"]
                        ResultPath: $.error
                        Next: NotifyFailure2
                    End: true

                  NotifyFailure2:
                    Type: Task
                    Resource: arn:aws:states:::sns:publish
                    Parameters:
                      TopicArn: !Ref StepFunctionFailureTopic
                      Message:
                        Child: Child2
                        Status: FAILED
                        Error.$: $.error
                    End: true

              # -------- Child 3 --------
              - StartAt: Child3
                States:
                  Child3:
                    Type: Task
                    Resource: arn:aws:states:::states:startExecution.sync
                    Parameters:
                      StateMachineArn: !Ref ChildGlueStepFunction
                      Input:
                        GlueJobs: []
                    Catch:
                      - ErrorEquals: ["States.ALL"]
                        ResultPath: $.error
                        Next: NotifyFailure3
                    End: true

                  NotifyFailure3:
                    Type: Task
                    Resource: arn:aws:states:::sns:publish
                    Parameters:
                      TopicArn: !Ref StepFunctionFailureTopic
                      Message:
                        Child: Child3
                        Status: FAILED
                        Error.$: $.error
                    End: true

              # -------- Child 4 --------
              - StartAt: Child4
                States:
                  Child4:
                    Type: Task
                    Resource: arn:aws:states:::states:startExecution.sync
                    Parameters:
                      StateMachineArn: !Ref ChildGlueStepFunction
                      Input:
                        GlueJobs: []
                    Catch:
                      - ErrorEquals: ["States.ALL"]
                        ResultPath: $.error
                        Next: NotifyFailure4
                    End: true

                  NotifyFailure4:
                    Type: Task
                    Resource: arn:aws:states:::sns:publish
                    Parameters:
                      TopicArn: !Ref StepFunctionFailureTopic
                      Message:
                        Child: Child4
                        Status: FAILED
                        Error.$: $.error
                    End: true

              # -------- Child 5 --------
              - StartAt: Child5
                States:
                  Child5:
                    Type: Task
                    Resource: arn:aws:states:::states:startExecution.sync
                    Parameters:
                      StateMachineArn: !Ref ChildGlueStepFunction
                      Input:
                        GlueJobs: []
                    Catch:
                      - ErrorEquals: ["States.ALL"]
                        ResultPath: $.error
                        Next: NotifyFailure5
                    End: true

                  NotifyFailure5:
                    Type: Task
                    Resource: arn:aws:states:::sns:publish
                    Parameters:
                      TopicArn: !Ref StepFunctionFailureTopic
                      Message:
                        Child: Child5
                        Status: FAILED
                        Error.$: $.error
                    End: true

            End: true

Outputs:
  MasterStepFunctionArn:
    Value: !Ref MasterStepFunction

  ChildStepFunctionArn:
    Value: !Ref ChildGlueStepFunction

  FailureTopicArn:
    Value: !Ref StepFunctionFailureTopic
